### ISSUE TITLE
Does EvalNE work with RDF data?

### ISSUE THREAD

**Issue by welsh01** [Dru-Mara/EvalNE#11]
Hello,
is this framework suitable with RDF data, since RDF induces a multigraph?

**Comment by Dru-Mara** [comment]
Hello,

I believe I have already answered your question via email. As I was saying there, in its current state, the framework is not able to correctly evaluate multigraphs. Some of the low-level functions will not work and for others, the behaviour might not be the expected one. The higher-level classes on the other hand should still be useful for this task. Therefore, I would recommend you to use the library as an API and build your own evaluation pipeline for multigraphs.

You can write us back if you have any technical issues and we will try to help out.

Regards,
Alex
