### ISSUE TITLE
[FEATURE] limiting thread usage

### ISSUE THREAD

**Issue by pstrybol** [Dru-Mara/EvalNE#12]
Hi, I found out when performing a benchmark experiment that at a certain point all available threads were used, this killed the process of a colleague of mine. I found the culprit to be the construction of the edge embeddings, this is written efficiently with Numpy but by default uses all available threads.

I tried to alter this behavior via joblib backend but that did not work.

I found solution which was to include the following 2 lines **before** importing numpy, in the script where I call the evalne evaluator:
`import os`
`os.environ["OPENBLAS_NUM_THREADS"] = "24"`

Note that the number of threads need to be given as a str not an int.

Hope this helps others with the same problem.

**Comment by Dru-Mara** [comment]
Thanks a lot for the heads-up on this issue and for sharing your solution. I will look into adding the option to limit the number of threads directly as a flag you can set prior to running an evaluation.

Alex

**Comment by Dru-Mara** [comment]
This issue was solved in version 0.3.4 of EvalNE. We've included a bash script that sets the maximum number of threads for numpy on a particular shell session. This script must be run before an evaluation with EvalNE. For more details check the README file under usage/parallelization.
