### ISSUE TITLE
[BUG] precisionatk (evaluation/score.py)

### ISSUE THREAD

**Issue by Pieter-PaulStrybol** [Dru-Mara/EvalNE#13]
Hi Alex,

I noticed this bug when I wanted to use the Score class separately from any other class in the evalne package, simply because it allows you to easily calculate and plot performance metrics. However, when I wanted to use the `precisionatk` function in *evalne/evaluation/score.py* at line 598 I got the following error:
- `TypeError: 'zip' object is not subscriptable`

Current solution: I solved it by first encapsulating the zip-object in a list-call as such `list(zip(*self._sorted))[0]` . 

Best,
Pieter-Paul

**Comment by Dru-Mara** [comment]
Hi,

Thanks for catching this! It seems it's a compatibility thing, in Python 2 unzipping returns lists while in Python 3 it returns an iterable from which you can not extract the first element. Your solution of casting to a list first works fine for both Python versions, so I've pushed a hotfix with this change.

Thanks again!
