### ISSUE TITLE
More a question than an issue

### ISSUE THREAD

**Issue by LPioL** [Dru-Mara/EvalNE#2]
Hi,
Is there a way ti use your package for custom network embedding method ?
Thank you.

**Comment by Dru-Mara** [comment]
Hello,

I'm not entirely sure what do you mean by custom embedding method. If you can elaborate a bit on it (maybe give an example), I can try to give you a more specific answer. 

However, as long as you have a method implemented in some programming language which can be 
executed from the command line (takes as parameters at least the input network to embed, the name of the output file which will contain the "results", and the dimensionality of the embedding) you can use the library to evaluate it. 

The "results" or output of your method can be the embeddings of every node in the network (as a dict or matrix), the embeddings corresponding to some given sets of train and test edges or the probabilities of the existence of an edge for given sets of train and test edges.

If you want to use the library as an API and import it in your code, like you would do with networkx or sklear for example, there are not many limits to what you can do with it :D  

Alex

**Comment by LPioL** [comment]
Hello,

Yes I am going to be more specific. I want to use your package as an API. And I already have my embeddings. I can't use directly your evaluator with my embeddings as input right ? I have to change the code for that. But maybe I missed something in the code.

Léo

**Comment by Dru-Mara** [comment]
Hi Léo,

Now I get what you want to do :), and yes it is possible to use the library as an API for evaluating the embeddings you've obtained with your own method. An example of how to do that would be:

```
# Load a graph from a given input path
G = pp.load_graph(input_path)

# Preprocess the graph to remove self-loops and relabel nodes sequentially 0...N 
G, ids = pp.prep_graph(G)

# Create an evaluator
nee = evaluator.Evaluator()

# Generate one train/test split with default parameters
nee.traintest_split.compute_splits(G, train_frac=0.9)

# Now the 'traintest_split' object contains sets of train (true and false edges)  
# and test (true and false edges). Also contains a 'train graph' generated from true train edges
# Depending on your method you can give it as input the train_edges
emb = my_node_embedding_method(nee.traintest_split.train_edges)

# Or the train graph to obtain the node embeddings
emb = my_node_embedding_method(nee.traintest_split.TG)

# Transform your node embeddings to a dict where the keys are nodeIDs and the values 
# are the associated embeddings for every vector
X = dict(zip(range(emb.shape[0]),emb))

# Now you can evaluate the embeddings and obtain a 'result' object
# You can call this function several times with different edge embedding methods
result = nee.evaluate_ne(data_split=nee.traintest_split, X=X, method="method_name_here", 
                                         edge_embed_method='hadamard')

# You can now, e.g. print the results of the link prediction evaluation 
result.pretty_print()
```

I will add soon another example, similar to the `examples/evaluator_example.py` but which will show how to evaluate your own embeddings in python.

I hope this helps,
Alex

**Comment by LPioL** [comment]
Sorry for the delay. Yes it helped a lot!
Do you think your code can also be applied for the evaluation of heterogeneous and mutiplex network embedding ?

**Comment by LPioL** [comment]
I try to test this example but I have a warning I don't understand:

nee.traintest_split.compute_splits(G, train_frac=0.95)
WARNING: In order to return a connected train set the train_frac parameter needs to be higher!
In this case, the provided train set constitutes a random spanning tree of the input graph.
The train_frac value used is: 1.0
Edges requested: train = 1.0, test = 0.0
Edges returned: train = 1, test = 0

Any help will be greatly appreciated.

**Comment by liujinxin1** [comment]
Hello, I also have the same problem. Please tell me how to test my method in this library. In fact, I encountered a problem in reproducing the tadw method in openne library. I wonder if you have reproduced this method?
